[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-static", "-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-static-libgcc", "-C", "link-arg=-static-libstdc++"]

[target.'cfg(target_os="macos")']
rustflags = [
    "-C", "link-args=-sectcreate __CGPreLoginApp __cgpreloginapp /dev/null",
]